api_checker/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "api_checker"

urlpatterns = [
    path("detail", views.detail, name="detail"),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
    path("mypage/", views.mypage, name="mypage"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo.views import base_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("pybo/", include("pybo.urls")),
    path("common/", include("common.urls")),
    path("recommend/", include("recommend.urls")),
    path("output/", include("output.urls")),
    path("predict/", include("predict.urls")),
    path("api_checker/", include("api_checker.urls")),
    path("", base_views.index, name="index"),  # '/' 에 해당되는 path
]

output/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "output"

urlpatterns = [
    path("predict/", views.predict, name="predict"),
]

predict/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "predict"

urlpatterns = [
    path("price/", views.price, name="price"),
]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

recommend/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "recommend"

urlpatterns = [
    path("predict/", views.predict, name="predict"),
]

common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

# UNIQUE constraint failed user_info.user_id
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone = models.CharField(max_length=20, null=True)
    area = models.CharField(max_length=20, null=True)
    location = models.CharField(max_length=20, null=True)
    month = models.IntegerField(null=True)

    def __str__(self):
        return self.user.username

predict/models.py
from django.db import models


class Predictiprice(models.Model):
    area = models.IntegerField()

    def __str__(self):
        return self.area

recommend/models.py
from django.db import models


class PredictionInput(models.Model):
    location = models.CharField(max_length=20, null=True)
    month = models.IntegerField(null=True)

    def __str__(self):
        return self.location, self.month

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    phone = forms.CharField(label="전화번호")
    area = forms.CharField(label="면적")
    location = forms.CharField(label="위치")

    class Meta:
        model = User
        fields = (
            "username",
            "password1",
            "password2",
            "email",
            "phone",
            "area",
            "location",
        )

predict/forms.py
from django import forms
from .models import Predictiprice


class PredictpriceForm(forms.Form):
    area = forms.IntegerField()

    class Meta:
        model = Predictiprice
        fields = (
            "area",
        )
        

recommend/forms.py
from django import forms
from .models import PredictionInput


class PredictForm(forms.Form):
    location = forms.CharField(label="지역")
    month = forms.IntegerField(error_messages={"required" : "월을 입력해 주세요."},label="월")

    class Meta:
        model = PredictionInput
        fields = (
            "location",
            "month",
        )
        

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import login as auth_login
from common.models import UserInfo
from common.forms import UserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm


# signup에서 사용자로 부터 면적, 위치, 전화번호를 받아옴
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            phone = form.cleaned_data.get("phone")
            area = form.cleaned_data.get("area")
            location = form.cleaned_data.get("location")
            # NOT NULL constraint failed common_userinfo.user_id
            UserInfo.objects.create(
                user=user, phone=phone, area=area, location=location
            )
            auth_login(request, user)
            return redirect("pybo:index")
    else:
        form = UserForm()
    return render(request, "common/signup.html", {"form": form})


# 로그인
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("pybo:index")
    else:
        form = AuthenticationForm()
    return render(request, "common/login.html", {"form": form})


# 로그아웃
def logout(request):
    auth_logout(request)
    return redirect("pybo:index")


# 마이페이지에서는 로그인한 사용자의 정보와 common uer_info df를 보여줌
@login_required(login_url="common:login")
def mypage(request):
    user = request.user
    user_info = UserInfo.objects.get(user=user)
    return render(request, "common/mypage.html", {"user_info": user_info})


# 회원탈퇴

predict/views.py
from django.shortcuts import render
import pickle
import joblib
from common.models import UserInfo
from django.contrib.auth.decorators import login_required
from .models import Predictiprice
from .forms import PredictpriceForm
from save_csv.models import baechoo_new
import pickle
import numpy as np
from django.http import HttpResponse

# 임의의 값
@login_required(login_url="common:login")
def price(request):
        return render(request, "common/predict.html")

templates/common/api_detail.html
{% extends "base.html" %}
{% block content %}
<!-- ---------------------- [edit] ------------------------ -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

<div class="row justify-content-center mb-2">
    <div class="col-md-12">
        <table class="table">
            <!-- pred 값 출력 -->
            <tr>
                <td type="text">
                    <font size="5em" color="green"> 입력한 면적값</font>
                </td>
                <th>
                    <input type="text" id="area" name="area" value="{{area}}" readonly>
                </th>
            </tr>
            <td type="text">
                <font size="5em" color="green">예상 생산량</font>
            <th>
                <input type="text" id="output" name="output" value="{{ output }}" readonly>
            </th>
            <tr>
                <br>
                <th>예상 가격</th>
                <td>가격</td>
                <td>예상 수익 확인하기</td>
            </tr>

            <tr>
                <th>1일 후 예상 가격</th>
                <td>{{ context.pred_1 }}</td>
                <td>
                    <script>
                        var pred_1 = {{ context.pred_1 }};
                        var output = {{ output }};
                        var result = pred_1 * output;
                        document.write(result);
                    </script>
                </td>
            </tr>
            <tr>
                <th>2일 후 예상 가격</th>
                <td>{{ context.pred_2 }}</td>
                <td>
                    <script>
                        var pred_2 = {{ context.pred_2 }};
                        var output = {{ output }};
                        var result = pred_2 * output;
                        document.write(result);
                    </script>
                </td>
            </tr>
            <tr>
                <th>3일 후 예상 가격</th>
                <td>{{ context.pred_3 }}</td>
                <td>
                    <script>
                        var pred_3 = {{ context.pred_3 }};
                        var output = {{ output }};
                        var result = pred_3 * output;
                        document.write(result);
                    </script>
                </td>
            </tr>
            <tr>
                <th>4일 후 예상 가격</th>
                <td>{{ context.pred_4 }}</td>
                <td>
                    <script>
                        var pred_4 = {{ context.pred_4 }};
                        var output = {{ output }};
                        var result = pred_4 * output;
                        document.write(result);
                    </script>
                </td>
            </tr>
            <tr>
                <th>5일 후 예상 가격</th>
                <td>{{ context.pred_5 }}</td>
                <td>
                    <script>
                        var pred_5 = {{ context.pred_5 }};
                        var output = {{ output }};
                        var result = pred_5 * output;
                        document.write(result);
                    </script>
                </td>
            </tr>
            <tr>
                <th>10일 후 예상 가격</th>
                <td>{{ context.pred_10 }}</td>
                <td>
                    <script>
                        var pred_10 = {{ context.pred_10 }};
                        var output = {{ output }};
                        var result = pred_10 * output;
                        document.write(result);
                    </script>
                </td>
            </tr>
            <tr>
                <th>20일 후 예상 가격</th>
                <td>{{ context.pred_20 }}</td>
                <td>
                    <script>
                        var pred_20 = {{ context.pred_20 }};
                        var output = {{ output }};
                        var result = pred_20 * output;
                        document.write(result);
                    </script>
                </td>
            </tr>
            <tr>
                <th>60일 후 예상 가격</th>
                <td>{{ context.pred_60 }}</td>
                <td>
                    <script>
                        var pred_60 = {{ context.pred_60 }};
                        var output = {{ output }};
                        var result = pred_60 * output;
                        document.write(result);
                    </script>
                </td>
            </tr>
            <tr>
                <th>120일 후 예상 가격</th>
                <td>{{ context.pred_120 }}</td>
                <td>
                    <script>
                        var pred_120 = {{ context.pred_120 }};
                        var output = {{ output }};
                        var result = pred_120 * output;
                        document.write(result);
                    </script>
                </td>
            </tr>
        </table>
        <th>
            금일 16시를 기준으로 금일 데이터가 반영됩니다. (*예시: 1/12일 3시에 생성된 그래프는 1/11일 기준입니다.)
        </th>
    </div>
</div>
<br>
<table>
    <tr>
        <div class="d-flex justify-content-center mb-2">
            <div class="d-flex justify-content-end">
                <a href="{% url 'output:predict' %}">
                    <button type="button" class="btn btn-primary">면적 재입력하기</button></a>
            </div>
        </div>
        <br>


        <!-- 4. 사이트 html 하단 figure 태그 -->
        <div class="highcharts-figure">
            <div id="container1"></div>
        </div>
        <!-- 6. script -->
        <script>
            var arr = new Array();
            for (var i = 1; i < 6; i++) {
                arr.push(i);
            }
            Highcharts.chart('container1', {
                chart: {
                    type: 'spline'
                },
                title: {
                    text: '일주일 가격 동향'
                },
                subtitle: {
                    text: '최근 일주일간 가격 현황'
                },
                xAxis: {
                    categories: arr
                },
                yAxis: {
                    title: {
                        text: 'Price'
                    },
                    labels: {
                        formatter: function () {
                            return this.value + '(원)';
                        }
                    }
                },
                tooltip: {
                    crosshairs: true,
                    shared: true
                },
                plotOptions: {
                    spline: {
                        marker: {
                            radius: 4,
                            lineColor: '#666666',
                            lineWidth: 1
                        }
                    }
                },
                series: [{
                    name: 'Price',
                    marker: {
                        symbol: 'diamond'
                    },
                    data: {{ item_5 }}

      }]
    });
        </script>
    </tr>
    <br>
    <tr>
        <!-- 4. 사이트 html 하단 figure 태그 -->
        <figure class="highcharts-figure">
            <div id="container2"></div>
        </figure>

        <!-- 6. script -->
        <script>
            var arr1 = new Array();
            for (var i = 1; i < 21; i++) {
                arr1.push(i);
            }
            Highcharts.chart('container2', {
                chart: {
                    type: 'spline'
                },
                title: {
                    text: '한 달 가격 동향'
                },
                subtitle: {
                    text: '최근 한 달 가격 현황'
                },
                xAxis: {
                    categories: arr1
                },
                yAxis: {
                    title: {
                        text: 'Price'
                    },
                    labels: {
                        formatter: function () {
                            return this.value + '(원)';
                        }
                    }
                },
                tooltip: {
                    crosshairs: true,
                    shared: true
                },
                plotOptions: {
                    spline: {
                        marker: {
                            radius: 4,
                            lineColor: '#666666',
                            lineWidth: 1
                        }
                    }
                },
                series: [{
                    name: 'Price',
                    marker: {
                        symbol: 'diamond'
                    },
                    data: {{ item_20 }}

      }]
    });
        </script>
    </tr>
    <br>
    <!-- 4. 사이트 html 하단 figure 태그 -->
    <figure class="highcharts-figure">
        <div id="container3"></div>
    </figure>

    <!-- 6. script -->
    <script>
        var arr2 = new Array();
        for (var i = 1; i < 366; i++) {
            arr2.push(i);
        }
        Highcharts.chart('container3', {
            chart: {
                type: 'spline'
            },
            title: {
                text: '일 년 가격 동향'
            },
            subtitle: {
                text: '최근 일 년간 가격 현황'
            },
            xAxis: {
                categories: arr2
            },
            yAxis: {
                title: {
                    text: 'Price'
                },
                labels: {
                    formatter: function () {
                        return this.value + '(원)';
                    }
                }
            },
            tooltip: {
                crosshairs: true,
                shared: true
            },
            plotOptions: {
                spline: {
                    marker: {
                        radius: 4,
                        lineColor: '#666666',
                        lineWidth: 1
                    }
                }
            },
            series: [{
                name: 'Price',
                marker: {
                    symbol: 'diamond'
                },
                data: {{ item_365 }}

      }]
    });
    </script>
</table>

{% endblock %}

templates/common/chart.html
{% extends "base.html" %}
<!-- index.html -->
{% load static %} 
<html>
<head>
<script>
window.onload = function () {
  var chart= new CanvasJS.Chart("chartContainer", {
    theme: "light2",
    title: {
      text: "Step Count Over a Week"
    },
    axisY: {
      title: "Number of Steps",
      stripLines: [{
        value: 10000,
        label: "Goal"
      }]
    },
    data: [{
      type: "line",
      yValueFormatString: "#,### Steps",
      dataPoints: {{ stepcount|safe }}
    }]
  });
  chart.render();
}
</script>    
</head>
<body>
    <div id="chartContainer" style="width: 100%; height: 360px;"></div>
    <script src="{% static 'canvasjs.min.js' %}"></script>
</body>
</html>                              

templates/common/chart_index.html
{% extends "base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
<div class="row justify-content-center mb-2">
    <div class="col-md-4">
        <br>
        <br>
        <div class="card" >
            <div class="card-body">
                <h5 class="card-title">일주일 가격 동향</h5>
                <a href="{% url 'api_checker:chart_5'%}" class="btn btn-primary">>> 자세히</a>
            </div>
            <div class="card-body">
                <h5 class="card-title">한 달 가격 동향</h5>
                <a href="{% url 'api_checker:chart_20'%}" class="btn btn-primary">>> 자세히</a>
            </div>
            <div class="card-body">
                <h5 class="card-title">일 년 가격 동향</h5>
                <a href="{% url 'api_checker:chart_365'%}" class="btn btn-primary">>> 자세히</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/common/info.html
<!-- 농산물 정보 다운로드 페이지 -->

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/predict.html
{% extends "base.html" %}
{% block content %}
<!-- y_p 값을 표시 -->
<div class="container my-3">
    <form method="post" action="{% url 'api_checker:detail' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <!-- 면적 : {{user_info.area}} -->
        <div class="form-group">
            <label for="area">면적</label>
            <input type="text" class="form-control" id="area" name="area" value="{{area}}">
            <div> ※ 면적 값을 수정하실 수 있습니다. </div>
            <!-- 제출 버튼 -->
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">가격예측 실행</button>
            </div>
            <br>
        </div>
    </form>
</div>
{% endblock %}

templates/common/recommend.html
<!-- y_p -->
<!-- Path: templates/common/recommend.html -->
{% extends "base.html" %}
{% block content %}
<!-- y_p 값을 표시 -->
<div class="container my-3">
    <form method="post" action="{% url 'recommend:predict' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <!-- location user_info.location-->
        <!-- location -->
        <div class="mb-3">
            <label for="location">지역</label>
            <select class="form-control" name="location" id="location">
                <!-- default value = user_info.location -->
                <option value="{{user_info.location}}" selected>{{user_info.location}}</option>
                <option value="제주도">제주도</option>
                <option value="부산광역시">부산광역시</option>
                <option value="대구광역시">대구광역시</option>
                <option value="인천광역시">인천광역시</option>
                <option value="광주광역시">광주광역시</option>
                <option value="대전광역시">대전광역시</option>
                <option value="울산광역시">울산광역시</option>
                <option value="세종특별자치시">세종특별자치시</option>
                <option value="경기도">경기도</option>
                <option value="강원도">강원도</option>
                <option value="충청북도">충청북도</option>
                <option value="충청남도">충청남도</option>
                <option value="전라북도">전라북도</option>
                <option value="전라남도">전라남도</option>
                <option value="경상북도">경상북도</option>
                <option value="경상남도">경상남도</option>
                <option value="제주도">제주특별자치도</option>
            </select>
        </div>
        <!-- 월 선택 -->
        <div class="mb-3">
            <label for="month">월</label>
            <select class="form-control" name="month" id="month">
                <!-- default value = user_info.month -->
                <option value="{{user_info.month}}" selected>선택하세요</option>
                <option value="1">1월</option>
                <option value="2">2월</option>
                <option value="3">3월</option>
                <option value="4">4월</option>
                <option value="5">5월</option>
                <option value="6">6월</option>
                <option value="7">7월</option>
                <option value="8">8월</option>
                <option value="9">9월</option>
                <option value="10">10월</option>
                <option value="11">11월</option>
                <option value="12">12월</option>
            </select>

        </div>


        <!-- 제출 버튼 -->
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-primary">결과 확인하기</button>
        </div>
        <br>
</div>
</form>
</div>
{% endblock %}

templates/common/recommend_op.html
<!-- y_p -->
<!-- Path: templates/common/recommend.html -->
{% extends "base.html" %}
{% block content %}
<!-- y_p 값을 표시 -->
<div class="container my-3">
    <form method="post" action="{% url 'output:predict' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <!-- 면적 : {{user_info.area}} -->
        <div class="form-group">
            <label for="area">면적</label>
            <input type="text" class="form-control" id="area" name="area" value="{{user_info.area}}">
            <div> ※ 면적 값을 수정하실 수 있습니다. </div>
            <!-- 제출 버튼 -->
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary">예측값 확인하기</button>
            </div>
            <br>
        </div>
    </form>
</div>
{% endblock %}

templates/common/result.html
<!-- y_p -->
<!-- Path: templates/common/recommend.html -->
{% extends "base.html" %}
{% block content %}
<!-- y_p 값을 표시 -->
<div class="container my-3">
    <form method="post" action="{% url 'recommend:predict' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <!-- location user_info.location-->
        <!-- location -->
        <div class="mb-3">
            <!-- 지역 -->
            <div class="mb-3">
                <label for="location">지역</label>
                <input type="text" class="form-control" name="location" id="location" value="{{ loc }}" readonly>
            </div>
            <!-- 월 -->
            <div class="mb-3">
                <div class="mb-3">
                    <labemonth">월</label>
                        <input type="text" class="form-control" name="month" id="month" value="{{ mon }}" readonly>
                </div>
                <!-- 배추재배 가능여부 -->
                <div class="mb-3">
                    <label for="cabbage">배추 재배 가능 여부</label>
                    <input type="text" class="form-control" name="cabbage" id="cabbage" value="{{ obj_test }}" readonly>
                    <br>
                    <div id="map">
                        <style>
                            #map {
                                width: 500px;
                                height: 400px;
                            }

                            #map {
                                margin: 0 auto;
                            }
                        </style>
                    </div>


                    <script type="text/javascript"
                        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=92e993d41176c18d60b08b50b4c84fa8&libraries=services,clusterer,drawing"></script>
                    <script>
                        // 지역별 위도, 경도
                        var locations = {
                            "서울특별시": {
                                "lat": 37.566826,
                                "lng": 126.9786567
                            },
                            "부산광역시": {
                                "lat": 35.1795543,
                                "lng": 129.0756416
                            },
                            "대구광역시": {
                                "lat": 35.8714354,
                                "lng": 128.601445
                            },
                            "인천광역시": {
                                "lat": 37.4562557,
                                "lng": 126.7052062
                            },
                            "광주광역시": {
                                "lat": 35.1595454,
                                "lng": 126.8526012
                            },
                            "대전광역시": {
                                "lat": 36.3504119,
                                "lng": 127.3845475
                            },
                            "울산광역시": {
                                "lat": 35.5383773,
                                "lng": 129.3113592
                            },
                            "세종특별자치시": {
                                "lat": 36.480048,
                                "lng": 127.289035
                            },
                            "경기도": {
                                "lat": 37.2752685,
                                "lng": 127.0094272
                            },
                            "강원도": {
                                "lat": 37.8858368,
                                "lng": 127.7298628
                            },
                            "충청북도": {
                                "lat": 36.6357099,
                                "lng": 127.4891256
                            },
                            "충청남도": {
                                "lat": 36.633309,
                                "lng": 126.916969
                            },
                            "전라북도": {
                                "lat": 35.7177971,
                                "lng": 127.153578
                            },
                            "전라남도": {
                                "lat": 34.810107,
                                "lng": 126.929506
                            },
                            "경상북도": {
                                "lat": 36.575844,
                                "lng": 128.505382
                            },
                            "경상남도": {
                                "lat": 35.1795543,
                                "lng": 128.0756416
                            },
                            "제주도": {
                                "lat": 33.361671,
                                "lng": 126.529214
                            }
                        };


                        // locations을 사용하여 지도를 생성합니다
                        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
                            mapOption = {
                                center: new kakao.maps.LatLng(locations["{{loc}}"].lat, locations["{{loc}}"].lng), // 지도의 중심좌표
                                level: 8 // 지도의 확대 레벨
                            };

                        var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다
                    </script>
                    <br>
                    <!-- 추천페이지 버튼 -->
                    <div class="d-flex justify-content-center">
                        <a href="{% url 'recommend:predict' %}"><button type="button" class="btn btn-primary">추천페이지로</button></a>
                    </div>
                    <br>
                </div>
    </form>
</div>
{% endblock %}

templates/common/result_output.html
<!-- y_p -->
<!-- Path: templates/common/recommend.html -->
{% extends "base.html" %}
{% block content %}
<!-- y_p 값을 표시 -->
<div class="container my-3">
    <form method="post" action="{% url 'output:predict' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <!-- location user_info.location-->
        <!-- location -->
        <div class="mb-3">
            <!-- 지역 -->
            <div class="mb-3">
                <label for="area">면적 (ha)</label>
                <input type="number" class="form-control" name="area" id="area" value="{{ area }}" readonly>
            </div>
        </div>
        <!-- 생산량 예측 -->
        <div class="mb-3">
            <label for="output">예측 생산량 값 (톤)</label>
            <input type="text" class="form-control" name="output" id="output" value="{{ output }}" readonly>

            <!-- 추천페이지 버튼 -->
            <br>

            <!-- 예측페이지 버튼 -->
            <br>

            <div class="d-flex justify-content-end">
                <a href="{% url 'output:predict' %}">
                    <button type="button" class="btn btn-primary">면적 재입력하기</button></a>
            <div style="margin-left:20px;"></div>
            <td class="d-flex justify-content-end">
                <a href="{% url 'api_checker:detail' %}">
                    <button type="button" class="btn btn-primary">가격예측하기</button></a>
            </td>
            </div>

    </form>
</div>
{% endblock %}